.TH HTICK 1 "Husky Tick v1.1.0" "09 July 2002" "Husky - Portable Fido Software"
.SH NAME
htick \- Husky File-Ticker
.SH SYNOPSIS
.B htick [-q] [-c config-file] <command>
.SH "OPTIONS"
.B -h
Print program name, version and usage information to screen and exit.
.B -v
Print program name and version to screen and exit.
.B -q
Quiet mode: don't print any messages to screen
.B -c config-file
Specify alternate config file
.SH "DESCRIPTION"
.SS "Tossen"
.B htick
reads *.tic Files in your Protected Inbound. According to the Information
/fBhtick/fR gets out of that *.tic Files it will process the received archives
and sort them into the filebase.
.SS "FileFix"
.B htick
has a builtin FileFix. A FileFix helps your users to maintain their area-subscriptions
without your interaction.
.SS "Hatch"
.B htick
could send files to FileEchos. This is called "to /fIhatch/fR" a File.
.SS "FileListe"
.B htick
makes a complete Filelist of your Filebase.
.SS "Announce"
.B htick
could tell you and your neigbours which files arrived. It could announce to
a specified echo or in a file (so you could process this file with some
scripts....)
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.SS "Main Commands"
.B toss
Reading *.tic and tossing files.
.br
.B scan
Scanning Netmail area for mails to filefix.
.br
.B hatch <file> <area> [<description>]
Hatch File <file> in in Area <area> with optional description.
.br
.B filelist <file> [<dirlist>]
Generate filelist which includes all files in Filebase.
<dirlist> - list of paths to files from filelist.
.br
.B send <file> <filearea> <address>
Send file from filearea to address.
.br
.B clean
Clean passthrough dir and old files in fileechos.
.SS "Optional Commands"
.B announce <area>
Announce new files in area (toss and hatch).
.br
.B annfecho <file>
Announce new fileecho in text file.
.br
.B replace [<filemask>]
Hatch file into Area, using Description for file, if exist "replace",
then fill replace field in TIC; if not exist <filemask>, then put <file>
in field.

.SH "RETURN VALUE"
.B 0
Success.
.SH ERRORS
.B 1
Error.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/fido/etc/config   'u
\fI/fido/etc/config\fR  Default Fidoconfig.
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at
http://husky.sourceforge.net/team.html.
.sp 1
Not all features are implemented yet, you are welcome to implement them :)
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).

